### ISSUE TITLE
flymake-easy made it easy to make flymake-solidity

### ISSUE THREAD

**Issue by kootenpv** [purcell/flymake-easy#6]
https://github.com/kootenpv/flymake-solidity

Thanks!

**Comment by purcell** [comment]
Yay, happy to hear that! I've personally switched over entirely to `flycheck` -- provided you have a fairly recent Emacs, I'd strongly suggest using that instead of `flymake`. It's better in many ways. See https://github.com/flycheck/flycheck

**Comment by kootenpv** [comment]
I know of flycheck, but on the surface there is nothing I can see that it does better.... Granted, I did install some extensions, but I got on the fly checking, sideline, tooltips, colors, configurable. I'm really curious what makes it better if you'd bother to answer?

**Comment by purcell** [comment]
There are a number of things I like. The ability to run multiple checkers per file is the big one, e.g. for a syntax checker plus a linter. Ability to have a separate error list displayed in a different window is nice. Also, you can write checkers in elisp - they don't always need to be external processes. And it's more actively maintained.
